name: Stagehands
favicon: null
layout_spectrum: 0.98911
typography_spectrum: 0.75545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#927361'
    - '#0c0c0c'
    - '#973b2e'
    - '#ccff7a'
  brandStrength: 0.4737929222173989
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
